[package]
name = "rintha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bunt = "0.2.6"
downloader = { version = "0.2.6", features = ["tui"] }
femtorinth = "0.1.2"
sha-1 = "0.9.8"
